#@ load("@ytt:data", "data")
kind: ConfigMap
apiVersion: v1
metadata:
  name: pos-receiver-config
data:
  SPRING_PROFILES_ACTIVE: receiver
  SPRING_RABBITMQ_HOST: tanzu-messaging-dc-rabbitmq.datacenter-database.svc.cluster.local
  SPRING_RABBITMQ_PASSWORD: #@ data.values.rabbitmq_password
  SPRING_RABBITMQ_USERNAME: #@ data.values.rabbitmq_username
  SPRING_DATASOURCE_USERNAME: #@ data.values.postgresql_username
  SPRING_DATASOURCE_PASSWORD: #@ data.values.postgresql_password
  SPRING_DATASOURCE_URL: "jdbc:postgresql://yb-tservers.dc-data-services.svc.cluster.local:5433"
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: #@ data.values.wavefrontProxyUri
