apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: dc-pos-messaging
spec:
  replicas: 1
  service:
    type: NodePort
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
