#@ load("@ytt:data", "data")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-receiver
  annotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "5678,5433"
spec:
  selector:
    matchLabels:
      app: pos-receiver
  replicas: 3 #! tells deployment to run 3 pods matching the template
  template: #! create pods using pod definition in this template
    metadata:
      labels:
        app: pos-receiver
    spec:
      containers:
      - name: receiver
        image: #@ data.values.image
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
        envFrom:
          - configMapRef:
              name: pos-receiver-config
      imagePullSecrets:
      - name: harbor-regcred
