apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-registry-creds        # must match source secret name
  namespace: rabbitmq-system  # must match source secret namespace
spec:
  toNamespaces:
  - "*"  # star means export is available for all namespaces
